version: 1.0.{build}
before_build:
- cmd: nuget restore src/ServiceStack.Logging.Slack.sln
build:
  project: src/ServiceStack.Logging.Slack.sln
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: 31RnoYihglJfGgdqHCpM3RRQspgU3cxK/gmIfgcj5ySW9uQVYM/7dxvEFpBrJjLz